[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bones"
version = "0.0.0"
description = "dice analysis toolkit"
authors = ["Bradd Szonye <bszonye@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/bszonye/bones"
repository = "https://github.com/bszonye/bones"
keywords = ["dice", "probability"]
packages = [
    { include = "bones" },
]

[tool.poetry.scripts]
bones = "bones.__main__:main"

[tool.poetry.dependencies]
python = "^3.11"
lea = "^3.4.2"
matplotlib = "^3.6.2"
PyGObject = "^3.42.2"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
flake8 = "^5.0.4"
flake8-bugbear = "^22.10.27"
flake8-docstrings = "^1.6.0"
flake8-isort = "^5.0.3"
isort = "^5.10.1"
mypy = "^0.991"
pydocstyle = "^6.1.1"
pytest = "^7.2.0"
pre-commit = "^2.20.0"

[tool.black]
line-length = 86

[tool.isort]
profile = "black"
line_length = 86
combine_as_imports = true
skip_gitignore = true

[tool.mypy]
strict = true
warn_no_return = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "lea.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "matplotlib.*"
ignore_missing_imports = true
